/* ============================================================
   E-COMMERCE SALES & CUSTOMER ANALYTICS
   ------------------------------------------------------------
   Sections:
     1. Primary Investigation (data exploration)
     2. Sales Analysis (revenue, profit, margin)
     3. Customer Analysis (CLV, AOV, segments, repeat rate)
     4. Time Analysis (growth, cohorts, retention, churn)
   ============================================================ */


/* ============================================================
   1. PRIMARY INVESTIGATION
   ============================================================ */

SELECT * FROM customers LIMIT 10;
SELECT * FROM order_items LIMIT 10;
SELECT * FROM orders LIMIT 10;
SELECT * FROM products LIMIT 10;
SELECT * FROM reviews LIMIT 10;

SELECT COUNT(*) AS total_customers FROM customers;
SELECT COUNT(*) AS total_order_items FROM order_items;
SELECT COUNT(*) AS total_orders FROM orders;
SELECT COUNT(*) AS total_products FROM products;
SELECT COUNT(*) AS total_reviews FROM reviews;


/* ============================================================
   2. SALES ANALYSIS
   Revenue, profit, monthly sales, product sales, profit margin
   ============================================================ */

-- Total revenue generated (all orders)
SELECT SUM(o.quantity * p.unit_price) AS total_revenue
FROM order_items o
JOIN products p
    ON o.product_id = p.product_id;

-- Total profit generated (all orders)
-- FIX: alias corrected from "total_revenue" to "total_profit"
SELECT SUM(o.quantity * ((p.unit_price - p.unit_cost) - o.discount)) AS total_profit
FROM order_items o
JOIN products p
    ON o.product_id = p.product_id;

-- Total revenue from completed orders only
SELECT ROUND(SUM(o.quantity * p.unit_price), 2) AS total_completed_revenue
FROM order_items o
JOIN products p
    ON o.product_id = p.product_id
JOIN orders od
    ON o.order_id = od.order_id
WHERE od.order_status = 'Completed';

-- Minimum, maximum, and average revenue generated by products
SELECT
    ROUND(MIN(total_revenue), 2) AS minimum_revenue,
    ROUND(AVG(total_revenue), 2) AS average_revenue,
    ROUND(MAX(total_revenue), 2) AS maximum_revenue
FROM (
    SELECT
        p.product_id,
        p.product_name,
        SUM(o.quantity * p.unit_price) AS total_revenue
    FROM products p
    JOIN order_items o
        ON p.product_id = o.product_id
    JOIN orders od
        ON o.order_id = od.order_id
    WHERE od.order_status = 'Completed'
    GROUP BY p.product_id, p.product_name
) AS product_sales;

-- Top 10 products by revenue
WITH total_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        ROUND(SUM(o.quantity * p.unit_price), 2) AS total_completed_revenue
    FROM products p
    JOIN order_items o
        ON p.product_id = o.product_id
    JOIN orders od
        ON o.order_id = od.order_id
    WHERE od.order_status = 'Completed'
    GROUP BY p.product_id, p.product_name
)
SELECT product_id, product_name, total_completed_revenue
FROM total_revenue
ORDER BY total_completed_revenue DESC
LIMIT 10;

-- Revenue vs. profit: top 10 products by profit (with margin)
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(o.quantity * p.unit_price), 2) AS total_completed_revenue,
    ROUND(SUM((o.quantity * p.unit_price) - (o.quantity * p.unit_cost)), 2) AS total_profit,
    ROUND(SUM((o.quantity * p.unit_price) - (o.quantity * p.unit_cost)) * 100
          / SUM(o.quantity * p.unit_price), 2) AS margin
FROM products p
JOIN order_items o
    ON p.product_id = o.product_id
JOIN orders od
    ON o.order_id = od.order_id
WHERE od.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY total_profit DESC
LIMIT 10;

-- Products generating at least $50,000 in revenue while maintaining a 30%+ margin
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(o.quantity * p.unit_price), 2) AS total_completed_revenue,
    ROUND(SUM((o.quantity * p.unit_price) - (o.quantity * p.unit_cost)), 2) AS total_profit,
    ROUND(SUM((o.quantity * p.unit_price) - (o.quantity * p.unit_cost)) * 100
          / SUM(o.quantity * p.unit_price), 2) AS margin
FROM products p
JOIN order_items o
    ON p.product_id = o.product_id
JOIN orders od
    ON o.order_id = od.order_id
WHERE od.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
HAVING margin >= 30 AND total_completed_revenue >= 50000
ORDER BY total_profit DESC;

-- Monthly revenue and month-over-month variance
-- added ORDER BY order_month inside the LAG() window so "previous month"
-- actually refers to the prior calendar
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(od.order_date, '%Y-%m') AS order_month,
        ROUND(SUM(o.quantity * p.unit_price), 2) AS total_completed_revenue
    FROM order_items o
    JOIN products p
        ON o.product_id = p.product_id
    JOIN orders od
        ON o.order_id = od.order_id
    WHERE od.order_status = 'Completed'
    GROUP BY order_month
)
SELECT
    order_month,
    total_completed_revenue,
    LAG(total_completed_revenue, 1, 0) OVER (ORDER BY order_month) AS previous_month_revenue,
    total_completed_revenue
        - LAG(total_completed_revenue, 1, total_completed_revenue) OVER (ORDER BY order_month) AS variance
FROM monthly_revenue;


/* ============================================================
   3. CUSTOMER ANALYSIS
   Customer lifetime value, average order value, segments, repeat customers
   ============================================================ */

-- Customer lifetime value (top 20 by revenue)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.customer_segment,
    SUM(od.quantity) AS total_quantity,
    COUNT(DISTINCT od.order_id) AS total_orders,
    SUM(od.quantity * p.unit_price) AS total_revenue,
    ROUND(SUM(od.quantity * p.unit_price) / COUNT(DISTINCT od.order_id), 2) AS average_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items od
    ON o.order_id = od.order_id
JOIN products p
    ON p.product_id = od.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, customer_name, c.customer_segment
ORDER BY total_revenue DESC
LIMIT 20;

-- Repeat customers (2+ completed orders)
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
    HAVING total_orders >= 2
)
SELECT
    COUNT(c.customer_id) AS total_customers,
    COUNT(co.customer_id) AS repeat_customers,
    ROUND(COUNT(co.customer_id) * 100 / COUNT(c.customer_id), 2) AS repeat_customer_percentage
FROM customers c
LEFT JOIN customer_orders co
    ON c.customer_id = co.customer_id;

-- Customer segments generating the most revenue
SELECT
    c.customer_segment,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    ROUND(SUM(p.unit_price * oi.quantity), 2) AS total_revenue,
    ROUND(SUM(p.unit_price * oi.quantity) / COUNT(DISTINCT oi.order_id), 2) AS avg_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON p.product_id = oi.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_segment
ORDER BY total_revenue DESC;


/* ============================================================
   4. TIME ANALYSIS
   Year-over-year growth, month-over-month growth, cohorts, churn
   ============================================================ */

-- Year-over-year growth
WITH yearly_revenue AS (
    SELECT
        YEAR(o.order_date) AS year,
        SUM(p.unit_price * oi.quantity) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON p.product_id = oi.product_id
    WHERE o.order_status = 'Completed'
    GROUP BY YEAR(o.order_date)
),
revenue_with_previous_year AS (
    SELECT
        year,
        revenue,
        LAG(revenue) OVER (ORDER BY year) AS previous_year_revenue
    FROM yearly_revenue
)
SELECT
    year,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_year_revenue, 2) AS previous_year_revenue,
    ROUND(((revenue - previous_year_revenue) / previous_year_revenue) * 100, 2) AS growth_percentage
FROM revenue_with_previous_year
ORDER BY year;

-- Month-over-month growth
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(od.order_date, '%Y-%m') AS order_month,
        ROUND(SUM(o.quantity * p.unit_price), 2) AS revenue
    FROM order_items o
    JOIN products p
        ON o.product_id = p.product_id
    JOIN orders od
        ON o.order_id = od.order_id
    WHERE od.order_status = 'Completed'
    GROUP BY order_month
),
previous_month_revenue AS (
    SELECT
        order_month,
        revenue,
        LAG(revenue) OVER (ORDER BY order_month) AS previous_month
    FROM monthly_revenue
)
SELECT
    order_month,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_month, 2) AS previous_month,
    ROUND(((revenue - previous_month) * 100 / previous_month), 2) AS growth
FROM previous_month_revenue
ORDER BY order_month;

-- Customer retention cohorts
-- How many customers from each first-purchase-month cohort came back in later months?
WITH first_purchase AS (
    SELECT
        customer_id,
        MIN(order_date) AS first_order,
        DATE_FORMAT(MIN(order_date), '%Y-%m') AS first_purchase_month
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
),
customer_activity AS (
    SELECT DISTINCT
        customer_id,
        DATE_FORMAT(order_date, '%Y-%m') AS purchase_month
    FROM orders
    WHERE order_status = 'Completed'
),
cohort_activity AS (
    SELECT
        fp.first_purchase_month,
        ca.purchase_month,
        COUNT(DISTINCT fp.customer_id) AS active_customers
    FROM first_purchase fp
    JOIN customer_activity ca
        ON fp.customer_id = ca.customer_id
    GROUP BY fp.first_purchase_month, ca.purchase_month
),
cohort_size AS (
    SELECT
        first_purchase_month,
        COUNT(DISTINCT customer_id) AS cohort_customers
    FROM first_purchase
    GROUP BY first_purchase_month
)
SELECT
    ca.first_purchase_month,
    ca.purchase_month,
    cs.cohort_customers,
    ca.active_customers,
    ROUND(ca.active_customers * 100.0 / cs.cohort_customers, 2) AS retention_percentage
FROM cohort_activity ca
JOIN cohort_size cs
    ON ca.first_purchase_month = cs.first_purchase_month
ORDER BY ca.first_purchase_month, ca.purchase_month;

-- Customer churn status (Active / At Risk / Churned)
-- NOTE: '2025-12-31' is used as a fixed snapshot/reference date for recency calculations
WITH last_purchase AS (
    SELECT
        customer_id,
        MAX(order_date) AS last_order_date
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
),
customer_recency AS (
    SELECT
        customer_id,
        last_order_date,
        DATEDIFF('2025-12-31', last_order_date) AS days_since_purchase
    FROM last_purchase
),
customer_status AS (
    SELECT
        customer_id,
        last_order_date,
        days_since_purchase,
        CASE
            WHEN days_since_purchase <= 600 THEN 'Active'
            WHEN days_since_purchase <= 700 THEN 'At Risk'
            ELSE 'Churned'
        END AS customer_status
    FROM customer_recency
)
SELECT
    customer_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100 / SUM(COUNT(*)) OVER (), 2) AS percentage_status
FROM customer_status
GROUP BY customer_status
ORDER BY customer_count DESC;

-- Churn rate (single KPI)
WITH last_purchase AS (
    SELECT
        customer_id,
        MAX(order_date) AS last_order_date
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
),
customer_recency AS (
    SELECT
        customer_id,
        last_order_date,
        DATEDIFF('2025-12-31', last_order_date) AS days_since_purchase
    FROM last_purchase
),
customer_status AS (
    SELECT
        customer_id,
        last_order_date,
        days_since_purchase,
        CASE
            WHEN days_since_purchase <= 600 THEN 'Active'
            WHEN days_since_purchase <= 700 THEN 'At Risk'
            ELSE 'Churned'
        END AS customer_status
    FROM customer_recency
)
SELECT
    COUNT(*) AS total_purchasing_customers,
    SUM(CASE WHEN customer_status = 'Churned' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN customer_status = 'Churned' THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS churn_rate
FROM customer_status;

-- Churn rate by customer segment
WITH last_purchase AS (
    SELECT
        customer_id,
        MAX(order_date) AS last_order_date
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
),
customer_recency AS (
    SELECT
        customer_id,
        last_order_date,
        DATEDIFF('2025-12-31', last_order_date) AS days_since_purchase
    FROM last_purchase
),
customer_status AS (
    SELECT
        customer_id,
        last_order_date,
        days_since_purchase,
        CASE
            WHEN days_since_purchase <= 600 THEN 'Active'
            WHEN days_since_purchase <= 700 THEN 'At Risk'
            ELSE 'Churned'
        END AS customer_status
    FROM customer_recency
)
SELECT
    c.customer_segment,
    COUNT(*) AS total_purchasing_customers,
    SUM(CASE WHEN cs.customer_status = 'Churned' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN cs.customer_status = 'Churned' THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS churn_rate
FROM customer_status cs
JOIN customers c
    ON cs.customer_id = c.customer_id
GROUP BY c.customer_segment
ORDER BY churn_rate;

-- Are high-revenue customers more likely to churn than low-revenue ones?

WITH customer_revenue AS (
    SELECT
        o.customer_id,
        ROUND(SUM(oi.quantity * p.unit_price), 2) AS total_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.customer_id
),
last_purchase AS (
    SELECT
        customer_id,
        MAX(order_date) AS last_order_date
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
),
customer_status AS (
    SELECT
        cr.customer_id,
        cr.total_revenue,
        lp.last_order_date,
        DATEDIFF('2025-12-31', lp.last_order_date) AS days_since_purchase,
        CASE
            WHEN DATEDIFF('2025-12-31', lp.last_order_date) <= 600 THEN 'Active'
            WHEN DATEDIFF('2025-12-31', lp.last_order_date) <= 700 THEN 'At Risk'
            ELSE 'Churned'
        END AS customer_status
    FROM customer_revenue cr
    JOIN last_purchase lp
        ON cr.customer_id = lp.customer_id
),
revenue_groups AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY total_revenue DESC) AS revenue_quartile
    FROM customer_status
)
SELECT
    revenue_quartile,
    COUNT(*) AS customers,
    SUM(CASE WHEN customer_status = 'Churned' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN customer_status = 'Churned' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM revenue_groups
GROUP BY revenue_quartile
ORDER BY revenue_quartile;